LATEX := pdflatex

.PHONY : all clean

all:
	$(LATEX) POLAR_High_Level_Data_Products_Format_Design_Specification.tex
	$(LATEX) POLAR_High_Level_Data_Products_Format_Design_Specification.tex

clean:
	@echo "cleaning ..."
	@rm -rf auto
	@rm -rf *.toc *.log *.out *.aux

