#ifndef ROOTINC_H
#define ROOTINC_H

#include "TFile.h"
#include "TTree.h"
#include "TH1.h"
#include "TH2.h"
#include "TF1.h"
#include "TCanvas.h"
#include "TApplication.h"
#include "TROOT.h"
#include "TMath.h"
#include "TStyle.h"
#include "TGraph.h"
#include "TGraphErrors.h"
#include "TGraph2D.h"
#include "TString.h"
#include "TPad.h"
#include "TMatrixF.h"
#include "TVectorF.h"
#include "TLine.h"
#include "TRandom3.h"
#include "TEventList.h"
#include "TNamed.h"
#include "TTimeStamp.h"
#include "TSystem.h"
#include "TLegend.h"
#include "TSpectrum.h"
#include "TH1.h"
#include "TPaveText.h"
#include "TProfile.h"
#include "TKey.h"
#include "THStack.h"

#endif
